some improvements
teknologi-umum/hacktoberfest pull request #47
Opened 2022-09-27 14:02 UTC by elianiva

- sort by difficulty
- exclude issues yg ga punya tag hacktoberfest
- pindahin default value ke file terpisah (kalo dipikir pikir ngapain ya, tapi gatau, tadi kepikiran, udah ketumpuk commit lain buat revert)
- ubah nama flag jadi snake_case biar lebih konsisten
- format stuff with rustfmt

2022-09-27 14:22 UTC, aldy505 requested changes

2022-09-27 14:22 UTC, aldy505 commented on backend/src/defaults.rs
> +pub const DEFAULT_GITHUB_TOKEN: &str = "";
udah kayak ngoding nodejs aja lu

2022-09-27 14:22 UTC, aldy505 commented on frontend/src/services/sort-issues.ts
> +    if (label.name === "difficulty: hard") return 3;
bagusnya ya, `label.name` ini di `.toLowerCase()` dulu

2022-09-27 14:22 UTC, aldy505 commented on frontend/src/services/sort-issues.ts
> +        if (a.labels.every((label) => !label.name.startsWith("difficulty: "))) {
sama ini, `label.name` di lowercase dulu

2022-09-27 14:22 UTC, aldy505 commented on frontend/src/services/sort-issues.ts
> +          return label.name.startsWith("difficulty") ? -1 : 0;
`label.name` di lowercase dulu

2022-09-27 14:22 UTC, aldy505 commented on frontend/src/services/sort-issues.ts
> +          return 1;
harusnya ini return 0, karena ga makes sense kalo ngga startsWith `difficulty` tapi tetep kena swap

2022-09-27 14:45 UTC, elianiva commented on frontend/src/services/sort-issues.ts
> +          return 1;
ini biar kena taruh dibawah

2022-09-28 00:10 UTC, aldy505 approved these changes
tunggu @ii64

2022-09-28 00:13 UTC, ii64 approved these changes

2022-09-28 00:13 UTC, ii64 commented
LGTM, there's some to improve on #48

2022-09-28 01:52 UTC, merged