feat(frontend): filter repositories that has no issue
teknologi-umum/hacktoberfest pull request #65
Opened 2022-10-09 15:24 UTC by up2dul

# Resolve on issue #56 
Here i filtered the repository list only showed repositories that has issue 

### Before
There is showed rosetta and manusier repo that has no issue
![Screenshot 2022-10-09 at 22-18-58 Hacktoberfest Teknologi Umum](https://user-images.githubusercontent.com/36098718/194764980-e1f78844-f3fc-49d4-ba10-6330c8db1621.png)

### After
![Screenshot 2022-10-09 at 22-19-34 Hacktoberfest Teknologi Umum](https://user-images.githubusercontent.com/36098718/194765041-db15a201-c286-4431-a052-e9f06e85c6ea.png)

2022-10-09 21:42 UTC, elianiva requested changes

2022-10-09 21:42 UTC, elianiva commented on frontend/src/routes/index.tsx
> +          .filter(({ issues }) => issues.length > 0)
filternya bukan disini harusnya, tapi disini
https://github.com/teknologi-umum/hacktoberfest/blob/f9eeab86188c75a9ae54ab74229e27c785e97211/frontend/src/services/filter-repositories.ts#L6

2022-10-11 04:54 UTC, up2dul commented on frontend/src/routes/index.tsx
> +          .filter(({ issues }) => issues.length > 0)
ternyata di file itu udah ada filter-nya ya, tapi gak ngefek apa-apa
![image](https://user-images.githubusercontent.com/36098718/195000347-9fe52c2a-5ef5-48ac-ae90-18d676e394db.png)

2022-10-11 05:26 UTC, elianiva commented on frontend/src/routes/index.tsx
> +          .filter(({ issues }) => issues.length > 0)
karena dia nunggu ada filter by labels, harusnya filter itu berlaku meskipun gaada labelsnya

2022-10-24 13:42 UTC, aldy505 commented
bump, siapa tau lupa

2023-08-24 01:23 UTC, aldy505 commented
Hello there. I'm gonna close this issue as we'll rewrite the repo soon enough.

2023-08-24 01:23 UTC, closed without merging